# Generated by Django 2.2.9 on 2020-02-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='分析流程名称')),
                ('pipeline_description', models.TextField(blank=True, null=True, verbose_name='分析流程描述')),
                ('pipeline_run_datetime', models.DateTimeField(blank=True, null=True, verbose_name='数据分析日期')),
                ('pipeline_run_by_who', models.CharField(blank=True, max_length=50, null=True, verbose_name='分析执行人')),
                ('result_description', models.TextField(blank=True, null=True, verbose_name='数据分析结果描述')),
                ('result_data_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='分析结果文件大小')),
                ('result_file_server', models.CharField(blank=True, max_length=50, null=True, verbose_name='分析结果存储服务器')),
                ('result_file_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='分析结果存储路径')),
                ('pipeline_notes', models.TextField(blank=True, null=True, verbose_name='分析流程备注')),
                ('pipeline_data_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline', to='data.Data', verbose_name='数据分析的原始数据来源')),
            ],
            options={
                'verbose_name': '分析流程',
                'verbose_name_plural': '分析流程',
            },
        ),
    ]
