# Generated by Django 2.2 on 2020-03-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('molecular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目名称')),
                ('porject_manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目负责人')),
                ('data_production_type', models.CharField(blank=True, choices=[('测序', '测序'), ('质谱', '质谱')], max_length=50, null=True, verbose_name='数据生产类型')),
                ('data_production_platform', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据生产平台')),
                ('data_production_datetime', models.DateTimeField(blank=True, null=True, verbose_name='数据生产时间')),
                ('data_production_notes', models.TextField(blank=True, null=True, verbose_name='数据生产备注')),
                ('data_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='原始数据类型')),
                ('data_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='原始数据大小')),
                ('md5_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='原始数据md5')),
                ('file_server', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据存储服务器')),
                ('file_path', models.CharField(blank=True, max_length=50, null=True, verbose_name='数据存储路径')),
                ('record_by_who', models.CharField(blank=True, max_length=50, null=True, verbose_name='记录添加人')),
                ('record_datetime', models.DateTimeField(auto_now_add=True, verbose_name='记录添加时间')),
                ('data_molecular_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='molecular.Molecular', verbose_name='分子的菌株来源')),
            ],
        ),
    ]
