# Generated by Django 2.2.9 on 2020-02-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strain', '0001_initial'),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目名称')),
                ('project_manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目负责人')),
                ('molecular_type', models.CharField(blank=True, choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('蛋白质', '蛋白质'), ('其它', '其它')], max_length=20, null=True, verbose_name='分子类型')),
                ('molecular_volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='分子的体积')),
                ('molecular_concentration', models.CharField(blank=True, max_length=50, null=True, verbose_name='分子的浓度')),
                ('molecular_store', models.CharField(blank=True, max_length=50, null=True, verbose_name='分子的存储方法')),
                ('molecular_box_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='分子的盒子ID')),
                ('return_or_not', models.BooleanField(blank=True, null=True, verbose_name='是否返样')),
                ('return_volumn', models.CharField(blank=True, max_length=50, null=True, verbose_name='返回的体积')),
                ('return_concentration', models.CharField(blank=True, max_length=50, null=True, verbose_name='返回的浓度')),
                ('return_notes', models.TextField(blank=True, null=True, verbose_name='返样备注信息')),
                ('record_by_who', models.CharField(blank=True, max_length=50, null=True, verbose_name='记录添加人')),
                ('record_datetime', models.DateTimeField(auto_now_add=True, verbose_name='记录添加时间')),
                ('molecular_sample_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='molecular', to='sample.Sample', verbose_name='分子的样本来源')),
                ('molecular_strain_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='molecular', to='strain.Strain', verbose_name='分子的菌株来源')),
            ],
        ),
    ]
