# Generated by Django 2.2 on 2020-03-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isolation_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='分离菌ID')),
                ('strain_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='菌株甘油管ID')),
                ('strain_box_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='菌株的盒子ID')),
                ('strain_usage', models.CharField(blank=True, max_length=50, null=True, verbose_name='菌株使用情况')),
                ('strain_store', models.CharField(blank=True, max_length=50, null=True, verbose_name='菌株保存方式')),
                ('stock_microbe', models.CharField(blank=True, max_length=50, null=True, verbose_name='收菌液体')),
                ('stock_date', models.DateField(blank=True, null=True, verbose_name='收菌日期')),
                ('part_of_gut', models.CharField(blank=True, choices=[('frozen_gut+glycerol', 'frozen_gut+glycerol'), ('midgut', 'midgut'), ('hindgut', 'hindgut'), ('ileum', 'ileum'), ('rectum', 'rectum')], max_length=50, null=True, verbose_name='肠道部位')),
                ('isolation_media', models.CharField(blank=True, max_length=50, null=True, verbose_name='培养基类型')),
                ('culture_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='培养条件')),
                ('culture_temperature', models.CharField(blank=True, max_length=10, null=True, verbose_name='培养温度')),
                ('culture_time', models.CharField(blank=True, max_length=10, null=True, verbose_name='培养时间/h')),
                ('isolate_by_who', models.CharField(blank=True, max_length=50, null=True, verbose_name='分离者姓名')),
                ('strain_phylum', models.CharField(blank=True, max_length=50, null=True, verbose_name='门')),
                ('strain_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='纲')),
                ('strain_order', models.CharField(blank=True, max_length=50, null=True, verbose_name='目')),
                ('strain_family', models.CharField(blank=True, max_length=50, null=True, verbose_name='科')),
                ('strain_genus', models.CharField(blank=True, max_length=50, null=True, verbose_name='属')),
                ('strain_tophit', models.CharField(blank=True, max_length=200, null=True, verbose_name='比对上菌种')),
                ('similarity_16s', models.IntegerField(blank=True, null=True, verbose_name='16s相似度-整数%')),
                ('blast_website', models.CharField(blank=True, max_length=100, null=True, verbose_name='比对网站')),
                ('ab1_quality', models.CharField(blank=True, max_length=5, null=True, verbose_name='测序质量')),
                ('blast_by_who', models.CharField(blank=True, max_length=20, null=True, verbose_name='比对人')),
                ('data_16s_filename', models.CharField(blank=True, max_length=100, null=True, verbose_name='测序文件名(seq & ab1)')),
                ('isolation_notes', models.TextField(blank=True, null=True, verbose_name='分离菌备注信息')),
                ('record_by_who', models.CharField(blank=True, max_length=50, null=True, verbose_name='记录添加人')),
                ('record_datetime', models.DateTimeField(auto_now_add=True, verbose_name='记录添加时间')),
                ('strain_sample_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strain', to='sample.Sample', verbose_name='菌株样本来源')),
            ],
            options={
                'verbose_name': '菌株信息总表',
                'verbose_name_plural': '菌株信息总表',
            },
        ),
    ]
